GRANT SELECT ON 职工 TO 王明;
GRANT SELECT ON 部门 TO 王明;
GRANT INSERT, DELETE ON 职工 TO 李勇;
GRANT INSERT, DELETE ON 部门 TO 李勇;
CREATE VIEW 职工个人信息 AS
SELECT *
FROM 职工
WHERE 职工号 = CURRENT_USER;
GRANT SELECT ON 职工个人信息 TO PUBLIC;
GRANT SELECT, UPDATE (工资) ON 职工 TO 刘星;
GRANT
ALTER
ON 职工 TO 张新; GRANT ALTER
ON 部门 TO 张新;
GRANT SELECT, INSERT, UPDATE, DELETE ON 职工 TO 周平;
GRANT SELECT, INSERT, UPDATE, DELETE ON 部门 TO 周平;
GRANT ALL PRIVILEGES ON 职工 TO 周平 WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON 部门 TO 周平 WITH GRANT OPTION;
CREATE VIEW 部门职工工资 AS
SELECT 部门.名称, MAX(职工.工资) AS 最高工资, MIN(职工.工资) AS 最低工资, AVG(职工.工资) AS 平均工资
FROM 部门
         JOIN 职工 ON 部门.部门号 = 职工.部门号
GROUP BY 部门.名称;
GRANT SELECT ON 部门职工工资 TO 杨兰;