#端口号
server:
  port: 9090

spring:
  #文件上传大小设置
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
#  redis:
#    host: 101.227.35.214
#    port: 6379
#    password:
#    timeout: 30000

  #数据源
  datasource:
    url: jdbc:mysql://mambamysql.mysql.rds.aliyuncs.com:3306/mamba?characterEncoding=utf8&useSSL=true
    username: root
    password: root123_
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000

#日志管理
logging:
  config: classpath:log/log4j3.yml

#mybatis
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: mambazzh.com.common.entity

#文件上传路径-本地
#upload-filePath: /Users/zzh/Desktop/file/

#文件上传路径-服务器
upload-filePath: /root/workspace/file_path/

# Mapper+实体类生成jar包： generatorConfig
db-location: lib/mysql-connector-java-5.46.jar





